/* Generated by the Nim Compiler v1.7.3 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33555805 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555171 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555179 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555178 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555175 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555176 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
var NNI33555176 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555176.node = NNI33555176;
NTI33555178.base = NTI33555175;
NTI33555179.base = NTI33555175;
var NNI33555175 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555178, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555179, name: "up", sons: null}]};
NTI33555175.node = NNI33555175;
var NNI33555171 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555171.node = NNI33555171;
NTI33555175.base = NTI33555171;
NTI33555176.base = NTI33555175;
NTI134217745.base = NTI33555176;
var NNI33555805 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554450, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554450, name: "Field2", sons: null}]};
NTI33555805.node = NNI33555805;
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
NTI134217741.base = NTI33555176;
NTI134217743.base = NTI134217741;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555176;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555176;

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557055, src_33557056, ti_33557057) {
  var result_33557066 = null;

    switch (ti_33557057.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_33557046(ti_33557057))) {
      result_33557066 = src_33557056;
      }
      else {
        result_33557066 = [src_33557056[0], src_33557056[1]];
      }
      
      break;
    case 19:
            if (dest_33557055 === null || dest_33557055 === undefined) {
        dest_33557055 = {};
      }
      else {
        for (var key in dest_33557055) { delete dest_33557055[key]; }
      }
      for (var key in src_33557056) { dest_33557055[key] = src_33557056[key]; }
      result_33557066 = dest_33557055;
    
      break;
    case 18:
    case 17:
      if (!((ti_33557057.base == null))) {
      result_33557066 = nimCopy(dest_33557055, src_33557056, ti_33557057.base);
      }
      else {
      if ((ti_33557057.kind == 17)) {
      result_33557066 = (dest_33557055 === null || dest_33557055 === undefined) ? {m_type: ti_33557057} : dest_33557055;
      }
      else {
        result_33557066 = (dest_33557055 === null || dest_33557055 === undefined) ? {} : dest_33557055;
      }
      }
      nimCopyAux(result_33557066, src_33557056, ti_33557057.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_33557056)) { 
        if(dest_33557055 === null || dest_33557055 === undefined || dest_33557055.length != src_33557056.length) {
          dest_33557055 = new src_33557056.constructor(src_33557056);
        } else {
          dest_33557055.set(src_33557056, 0);
        }
        result_33557066 = dest_33557055;
      } else {
        if (src_33557056 === null) {
          result_33557066 = null;
        }
        else {
          if (dest_33557055 === null || dest_33557055 === undefined || dest_33557055.length != src_33557056.length) {
            dest_33557055 = new Array(src_33557056.length);
          }
          result_33557066 = dest_33557055;
          for (var i = 0; i < src_33557056.length; ++i) {
            result_33557066[i] = nimCopy(result_33557066[i], src_33557056[i], ti_33557057.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_33557056 === null) {
        result_33557066 = null;
      }
      else {
        if (dest_33557055 === null || dest_33557055 === undefined || dest_33557055.length != src_33557056.length) {
          dest_33557055 = new Array(src_33557056.length);
        }
        result_33557066 = dest_33557055;
        for (var i = 0; i < src_33557056.length; ++i) {
          result_33557066[i] = nimCopy(result_33557066[i], src_33557056[i], ti_33557057.base);
        }
      }
    
      break;
    case 28:
            if (src_33557056 !== null) {
        result_33557066 = src_33557056.slice(0);
      }
    
      break;
    default: 
      result_33557066 = src_33557056;
      break;
    }

  return result_33557066;

}

function arrayConstr(len_33557094, value_33557095, typ_33557096) {
        var result = new Array(len_33557094);
    for (var i = 0; i < len_33557094; ++i) result[i] = nimCopy(null, value_33557095, typ_33557096);
    return result;
  

  
}

function mnewString(len_33556808) {
        return new Array(len_33556808);
  

  
}

function addInt(a_33556855, b_33556856) {
        var result = a_33556855 + b_33556856;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_33557104, a_33557105, b_33557106) {
  var result_33557107 = 0;

  BeforeRet: {
    if (((a_33557105 <= i_33557104) && (i_33557104 <= b_33557106))) {
    result_33557107 = i_33557104;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557107;

}

function chckIndx(i_33557099, a_33557100, b_33557101) {
  var result_33557102 = 0;

  BeforeRet: {
    if (((a_33557100 <= i_33557099) && (i_33557099 <= b_33557101))) {
    result_33557102 = i_33557099;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_33557099, a_33557100, b_33557101);
    }
    
  };

  return result_33557102;

}

function cstrToNimstr(c_33556719) {
      var ln = c_33556719.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_33556719.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_33556719.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function toJSStr(s_33556722) {
  var result_33556723 = null;

    var res_33556757 = newSeq_33556740((s_33556722).length);
    var i_33556758 = 0;
    var j_33556759 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556758 < (s_33556722).length)) break Label2;
          var c_33556760 = s_33556722[i_33556758];
          if ((c_33556760 < 128)) {
          res_33556757[j_33556759] = String.fromCharCode(c_33556760);
          i_33556758 += 1;
          }
          else {
            var helper_33556772 = newSeq_33556740(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556773 = c_33556760.toString(16);
                  if ((((code_33556773) == null ? 0 : (code_33556773).length) == 1)) {
                  helper_33556772.push("%0");;
                  }
                  else {
                  helper_33556772.push("%");;
                  }
                  
                  helper_33556772.push(code_33556773);;
                  i_33556758 += 1;
                  if ((((s_33556722).length <= i_33556758) || (s_33556722[i_33556758] < 128))) {
                  break Label3;
                  }
                  
                  c_33556760 = s_33556722[i_33556758];
                }
            };
++excHandler;
            try {
            res_33556757[j_33556759] = decodeURIComponent(helper_33556772.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556757[j_33556759] = helper_33556772.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556759 += 1;
        }
    };
    if (res_33556757.length < j_33556759) { for (var i = res_33556757.length ; i < j_33556759 ; ++i) res_33556757.push(null); }
               else { res_33556757.length = j_33556759; };
    result_33556723 = res_33556757.join("");

  return result_33556723;

}

function raiseException(e_33556582, ename_33556583) {
    e_33556582.name = ename_33556583;
    if ((excHandler == 0)) {
    unhandledException(e_33556582);
    }
    
    e_33556582.trace = nimCopy(null, rawWriteStackTrace_33556546(), NTI33554449);
    throw e_33556582;

  
}

function makeNimstrLit(c_33556716) {
      var result = [];
  for (var i = 0; i < c_33556716.length; ++i) {
    result[i] = c_33556716.charCodeAt(i);
  }
  return result;
  

  
}
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole_examples_2", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsconsole_examples_2.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function isFatPointer_33557046(ti_33557047) {
  var result_33557048 = false;

  BeforeRet: {
    result_33557048 = !((ConstSet1[ti_33557047.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557048;

}

function nimCopyAux(dest_33557059, src_33557060, n_33557061) {
    switch (n_33557061.kind) {
    case 0:
      break;
    case 1:
            dest_33557059[n_33557061.offset] = nimCopy(dest_33557059[n_33557061.offset], src_33557060[n_33557061.offset], n_33557061.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_33557061.sons.length; i++) {
      nimCopyAux(dest_33557059, src_33557060, n_33557061.sons[i]);
    }
    
      break;
    case 3:
            dest_33557059[n_33557061.offset] = nimCopy(dest_33557059[n_33557061.offset], src_33557060[n_33557061.offset], n_33557061.typ);
      for (var i = 0; i < n_33557061.sons.length; ++i) {
        nimCopyAux(dest_33557059, src_33557060, n_33557061.sons[i][1]);
      }
    
      break;
    }

  
}

function add_33556373(x_33556374, x_33556374_Idx, y_33556375) {
          if (x_33556374[x_33556374_Idx] === null) { x_33556374[x_33556374_Idx] = []; }
      var off = x_33556374[x_33556374_Idx].length;
      x_33556374[x_33556374_Idx].length += y_33556375.length;
      for (var i = 0; i < y_33556375.length; ++i) {
        x_33556374[x_33556374_Idx][off+i] = y_33556375.charCodeAt(i);
      }
    

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_33556853) {
        if (a_33556853 > 2147483647 || a_33556853 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function raiseIndexError(i_33556669, a_33556670, b_33556671) {
    var Temporary1;

    if ((b_33556671 < a_33556670)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32] || []).concat(HEX24_352321544(i_33556669) || [],[32,110,111,116,32,105,110,32] || [],HEX24_352321544(a_33556670) || [],[32,46,46,32] || [],HEX24_352321544(b_33556671) || []);
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function addChars_285212847(result_285212849, result_285212849_Idx, x_285212850, start_285212851, n_285212852) {
  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 43;
    var old_285212853 = (result_285212849[result_285212849_Idx]).length;
    F.line = 44;
    (result_285212849[result_285212849_Idx].length = chckRange(addInt(old_285212853, n_285212852), 0, 2147483647));
    Label1: {
      F.line = 46;
      var iHEX60gensym4_285212867 = 0;
      F.line = 119;
      var i_637534243 = 0;
      Label2: {
        F.line = 120;
          Label3: while (true) {
          if (!(i_637534243 < n_285212852)) break Label3;
            F.line = 49;
            iHEX60gensym4_285212867 = i_637534243;
            F.line = 49;
            result_285212849[result_285212849_Idx][chckIndx(addInt(old_285212853, iHEX60gensym4_285212867), 0, (result_285212849[result_285212849_Idx]).length - 1)] = x_285212850.charCodeAt(chckIndx(addInt(start_285212851, iHEX60gensym4_285212867), 0, (x_285212850).length - 1));
            F.line = 122;
            i_637534243 = addInt(i_637534243, 1);
          }
      };
    };
  framePtr = F.prev;

  
}

function addChars_285212843(result_285212845, result_285212845_Idx, x_285212846) {
  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 55;
    addChars_285212847(result_285212845, result_285212845_Idx, x_285212846, 0, ((x_285212846) == null ? 0 : (x_285212846).length));
  framePtr = F.prev;

  
}

function addInt_285212868(result_285212869, result_285212869_Idx, x_285212870) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 113;
    addChars_285212843(result_285212869, result_285212869_Idx, ((x_285212870) + ""));
  framePtr = F.prev;

  
}

function addInt_285212889(result_285212890, result_285212890_Idx, x_285212891) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 117;
    addInt_285212868(result_285212890, result_285212890_Idx, x_285212891);
  framePtr = F.prev;

  
}

function HEX24_352321544(x_352321545) {
  var result_352321546 = [[]];

  var F = {procname: "dollars.$", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/dollars.nim", line: 0};
  framePtr = F;
    F.line = 18;
    addInt_285212889(result_352321546, 0, x_352321545);
  framePtr = F.prev;

  return result_352321546[0];

}

function auxWriteStackTrace_33556474(f_33556475) {
  var result_33556476 = [[]];

    var it_33556484 = f_33556475;
    var i_33556485 = 0;
    var total_33556486 = 0;
    var tempFrames_33556487 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555805);
    Label1: {
        Label2: while (true) {
        if (!(!((it_33556484 == null)) && (i_33556485 <= 63))) break Label2;
          tempFrames_33556487[i_33556485].Field0 = it_33556484.procname;
          tempFrames_33556487[i_33556485].Field1 = it_33556484.line;
          tempFrames_33556487[i_33556485].Field2 = it_33556484.filename;
          i_33556485 += 1;
          total_33556486 += 1;
          it_33556484 = it_33556484.prev;
        }
    };
    Label3: {
        Label4: while (true) {
        if (!!((it_33556484 == null))) break Label4;
          total_33556486 += 1;
          it_33556484 = it_33556484.prev;
        }
    };
    result_33556476[0] = nimCopy(null, [], NTI33554449);
    if (!((total_33556486 == i_33556485))) {
    result_33556476[0].push.apply(result_33556476[0], [40]);;
    result_33556476[0].push.apply(result_33556476[0], HEX24_352321544((total_33556486 - i_33556485)));;
    result_33556476[0].push.apply(result_33556476[0], [32,99,97,108,108,115,32,111,109,105,116,116,101,100,41,32,46,46,46,10]);;
    }
    
    Label5: {
      var j_33556517 = 0;
      var colontmp__637534235 = 0;
      colontmp__637534235 = (i_33556485 - 1);
      var res_637534237 = colontmp__637534235;
      Label6: {
          Label7: while (true) {
          if (!(0 <= res_637534237)) break Label7;
            j_33556517 = res_637534237;
            result_33556476[0].push.apply(result_33556476[0], cstrToNimstr(tempFrames_33556487[j_33556517].Field2));;
            if ((0 < tempFrames_33556487[j_33556517].Field1)) {
            result_33556476[0].push.apply(result_33556476[0], [40]);;
            addInt_285212889(result_33556476, 0, tempFrames_33556487[j_33556517].Field1);
            if (false) {
            result_33556476[0].push.apply(result_33556476[0], [44,32]);;
            addInt_285212889(result_33556476, 0, 0);
            }
            
            result_33556476[0].push.apply(result_33556476[0], [41]);;
            }
            
            result_33556476[0].push.apply(result_33556476[0], [32,97,116,32]);;
            add_33556373(result_33556476, 0, tempFrames_33556487[j_33556517].Field0);
            result_33556476[0].push.apply(result_33556476[0], [10]);;
            res_637534237 -= 1;
          }
      };
    };

  return result_33556476[0];

}

function rawWriteStackTrace_33556546() {
  var result_33556547 = [];

    if (!((framePtr == null))) {
    result_33556547 = nimCopy(null, ([84,114,97,99,101,98,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,108,97,115,116,41,10] || []).concat(auxWriteStackTrace_33556474(framePtr) || []), NTI33554449);
    }
    else {
      result_33556547 = nimCopy(null, [78,111,32,115,116,97,99,107,32,116,114,97,99,101,98,97,99,107,32,97,118,97,105,108,97,98,108,101,10], NTI33554449);
    }
    

  return result_33556547;

}

function newSeq_33556740(len_33556742) {
  var result_33556743 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 604;
    result_33556743 = new Array(len_33556742); for (var i = 0 ; i < len_33556742 ; ++i) { result_33556743[i] = null; }  framePtr = F.prev;

  return result_33556743;

}

function unhandledException(e_33556578) {
    var buf_33556579 = [[]];
    if (!(((e_33556578.message).length == 0))) {
    buf_33556579[0].push.apply(buf_33556579[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556579[0].push.apply(buf_33556579[0], e_33556578.message);;
    }
    else {
    buf_33556579[0].push.apply(buf_33556579[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556579[0].push.apply(buf_33556579[0], [32,91]);;
    add_33556373(buf_33556579, 0, e_33556578.name);
    buf_33556579[0].push.apply(buf_33556579[0], [93,10]);;
    buf_33556579[0].push.apply(buf_33556579[0], rawWriteStackTrace_33556546());;
    var cbuf_33556580 = toJSStr(buf_33556579[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556580);
  }
  else {
    throw cbuf_33556580;
  }
  

  
}

function raiseAssert_251658262(msg_251658263) {
  var F = {procname: "assertions.raiseAssert", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 31;
    raiseException({message: nimCopy(null, msg_251658263, NTI33554449), parent: null, m_type: NTI134217745, name: null, trace: [], up: null}, "AssertionDefect");
  framePtr = F.prev;

  
}

function failedAssertImpl_251658292(msg_251658293) {
  var F = {procname: "assertions.failedAssertImpl", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 41;
    raiseAssert_251658262(msg_251658293);
  framePtr = F.prev;

  
}
var F = {procname: "module jsconsole_examples_2", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsconsole_examples_2.nim", line: 0};
framePtr = F;
F.line = 101;
console.assert(true, "[jsAssert] /home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsconsole_examples_2.nim(8, 10)","42 == 42");
F.line = 101;
console.assert(false, "[jsAssert] /home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsconsole_examples_2.nim(9, 10)","42 != 42");
F.line = 101;
console.assert(false, "[jsAssert] /home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsconsole_examples_2.nim(10, 10)","\'`\' == \'\\n\' and \'\\t\' == \'\\x00\'");
if (false) {
F.line = 101;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsconsole_examples_2.nim(11, 10) `42 == 42` "));
}

framePtr = F.prev;
var F = {procname: "module jsconsole_examples_2", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsconsole_examples_2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole_examples_2", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsconsole_examples_2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole_group1_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsconsole_group1_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole_group1_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsconsole_group1_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
